a = 8;
document.write (a*=3);
document.write("<br/>");
document.write (a/=2);
document.write("<br/>");
document.write(a%=5);
document.write("<br/>");
document.write(a+=3);
document.write("<br/>");
document.write (a-=1);
document.write("<br/>");